apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: minishop-prod

replicas:
  - name: minishop-backend
    count: 5

image:
  - name: nginx
    newName: nginx
    tag: stable-perl

configMapGenerator:
  - name: minishop-config
    behavior: merge
    literals:
      - log_level=warn      
      - host: prod-db-svc.minishop-prod.svc.cluster.local