apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
  namespace: notify-service-ns
spec:
  scaleTargetRef:
    apiVerion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 2
  maxReplicas: 20
 
  metrics:
  - type: Resources
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 2
        periodSeconds: 30