apiVersion: v1
kind: LimitRange
metadata:
  name: not-serv-lr
  namespace: notify-service-ns
spec:
  limits:
  - default:
      memory: "512Mi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "250m"
    max:
      memory: "2Gi"
      cpu: "2"
    min:
      memory: "64Mi"
      cpu: "125m"
    type: Container 