apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: notify-service-ns
type: Opaque
stringData:
  sendgrid-api-key: "SG.tz2m-***REDACTED-STAGING***"
  dbpassword: "nonlaconosci"
  user: "notify_app_user"