namespace:
  name: notifyservice
  environment1: staging
  environment2: prod

resquota:
  name: notifyserviceresquota
  rc: "2"
  rm: "4Gi"
  lc: "4"
  lm: "8Gi"
  count:
    pods: "10"
    services: "5"
    configmaps: "10"
    secrets: "10"
    pvcs: "2"

  prc: "6"
  prm: "10Gi"
  plc: "10"
  plm: "26Gi"
  pcount:
    pods: "20"
    services: "10"
    configmaps: "20"
    secrets:  "20"
    pvcs: "4"

limitrange:
  name: notifyservicelimitrange
  lm: "512Mi"
  lc: "500m"
  dm: "256Mi"
  dc: "250m"
  mxc: "2Gi"
  mxm: "2"
  mnc: "64Mi"
  mnm: "100m"

kreq:
  name: podpolicies

kreq1:
  name: require-requests-limits
  annotations: 
    policies.kyverno.io/title: "Require Resource and limits"
    policies.kyverno.io/category: "Best Practice"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/description: "Check resources and limits as policy."
  val: "?"

kreq2:
  name: not-latest-as-label
  annotations:
    policies.kyverno.io/title: "No latest as tag"
    policies.kyverno.io/category: "Best Practice"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/description: "No :latest as image tag"
  val: "*:*"
  val2: "!*:latest"

kreq3:
  name: require-nonroot
  annotations:
    policies.kyverno.io/title: "Non root"
    policies.kyverno.io/category: "Best Practice"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/description: "Container obliged in non-root usr"
  val: true

kreq4:
  name: required-labels
  annotations:
    policies.kyverno.io/title: "Label Required for NS and Pods"
    policies.kyverno.io/category: "Best Practice"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/description: "Must-have-label Namespace&Pods Policy"
  val: "staging | production"

kreq5:
  name: rollingupdate
  annotations:
    policies.kyverno.io/title: "RollingUpdate policy"
    policies.kyverno.io/category: "Best Practice"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/description: "Define quotas"
  val: "!0"

kreq6:
  name: pvc-size-limit
  annotations:
    policies.kyverno.io/title: "PVC size limit"
    policies.kyverno.io/category: "Best Practice"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/description: "Defined and limited PVC size"
  val: "<=30Gi"

storageClass:
  name: storage-ssd
  provisioner: kubernetes.io/no-provisioner
  reclaimPolicy: Retain
  volumeBindingMode: Immediate
  allowVolumeExpansion: true

hpa:
  name: hps-notifyservice
  min: "2"
  max: "10"