apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Values.authorizationPolicy.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.authorizationPolicy.selector | nindent 6 }}
  action: {{ .Values.authorizationPolicy.action }}
  rules:
  - from:
    - source:
        principals:
        - {{ .Values.authorizationPolicy.principal }}
