apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
data:
  db-host: {{ .Values.configMap.dbHost | quote }}
  db-port: {{ .Values.configMap.dbPort | quote }}
  db-user: {{ .Values.configMap.dbUser | quote }}
  db-name: {{ .Values.configMap.dbName | quote }}
  log-level: {{ .Values.configMap.logLevel | quote }}
