apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
      version: {{ .Values.backend.version }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        version: {{ .Values.backend.version }}
        {{- include "orderhub.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        resources:
          {{- toYaml .Values.backend.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.readinessProbe.path }}
            port: {{ .Values.backend.readinessProbe.port }}
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.livenessProbe.path }}
            port: {{ .Values.backend.livenessProbe.port }}
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.backend.configMapName }}
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.backend.configMapName }}
              key: db-port
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.backend.configMapName }}
              key: db-user
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.backend.configMapName }}
              key: db-name
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.backend.configMapName }}
              key: log-level
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.backend.secretName }}
              key: db-password
