apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.impulse.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.impulse.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.impulse.name }}
    spec:
      containers:
      - name: {{ .Values.impulse.name }}
        image: "{{ .Values.impulse.image.repository }}:{{ .Values.impulse.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.impulse.port }}
        resources:
          requests:
            memory: {{ .Values.impulse.resources.requests.memory }}
            cpu: {{ .Values.impulse.resources.requests.cpu }}
          limits:
            memory: {{ .Values.impulse.resources.limits.memory }}
            cpu: {{ .Values.impulse.resources.limits.cpu }}