apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.impulse.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
    app: {{ .Values.impulse.name }}
spec:
  replicas: {{ .Values.impulse.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.impulse.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.impulse.name }}
    spec:
      containers:
      - name: {{ .Values.impulse.name }}
        image: "{{ .Values.impulse.image.repository }}:{{ .Values.impulse.image.tag }}"
        imagePullPolicy: {{ .Values.impulse.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.impulse.port }}
        resources:
          {{- toYaml .Values.impulse.resources | nindent 10 }}
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: dbHost
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: dbName
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.configmap.name }}
              key: dbUser
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: dbPassword 
