apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Values.peerauth.name }}
  namespace: {{ include "orderhub.namespace" . }}
spec:
  mtls:
    mode: {{ .Values.peerauth.mode }}
