apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
    {{- toYaml .Values.persistentVolume.labels | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.size }}
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolume.reclaimPolicy }}
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
    type: {{ .Values.persistentVolume.hostPathType }}
