apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.podMonitor.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.podMonitor.labels | nindent 4 }}
spec:
  selector:
    matchExpressions:
    - key: security.istio.io/tlsMode
      operator: Exists
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: {{ .Values.podMonitor.port }}
    path: {{ .Values.podMonitor.path }}
    interval: {{ .Values.podMonitor.interval }}
