apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.promtailConfig.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
data:
  promtail-config.yaml: |
    server:
      http_listen_port: {{ .Values.promtailConfig.httpListenPort }}

    clients:
      - url: {{ .Values.promtailConfig.lokiUrl | quote }}

    scrape_configs:
      - job_name: orderhub-pods
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - {{ .Values.promtailConfig.scrapeNamespace }}
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - source_labels: [__meta_kubernetes_container_name]
            target_label: container
          - source_labels: [__meta_kubernetes_pod_label_app]
            target_label: app
        pipeline_stages:
          - match:
              selector: '{app=~"{{ .Values.promtailConfig.appSelector }}"}'
              stages:
                - docker: {}
                - regex:
                    expression: '.*(?P<level>ERROR|WARN|INFO|DEBUG).*'
                - labels:
                    level: level
