apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.promtail.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.promtail.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.promtail.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchFields:
              - key: metadata.name
                operator: NotIn
                values:
                {{- toYaml .Values.promtail.excludeNodes | nindent 16 }}
      serviceAccountName: {{ .Values.promtailServiceAccount.name }}
      containers:
      - name: {{ .Values.promtail.name }}
        image: "{{ .Values.promtail.image.repository }}:{{ .Values.promtail.image.tag }}"
        imagePullPolicy: {{ .Values.promtail.image.pullPolicy }}
        args:
        - -config.file=/etc/promtail/promtail-config.yaml
        volumeMounts:
        - name: config-volume
          mountPath: /etc/promtail
        - name: logs
          mountPath: /var/log/pods
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.promtail.configMapName }}
      - name: logs
        hostPath:
          path: /var/log/pods
