apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
    {{- toYaml .Values.persistentVolumeClaim.labels | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistentVolumeClaim.accessModes | nindent 4 }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.size }}
