apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.resourceQuota.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
spec:
  hard:
    {{- toYaml .Values.resourceQuota.hard | nindent 4 }}
