apiVersion: v1
kind: Secret
metadata:
  name: orderhub-secret
  namespace: {{ include "orderhub.namespace" . }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.secret.dbPassword | quote }}
