apiVersion: v1
kind: Service
metadata:
  name: orderhub-backend-svc
  namespace: {{ include "orderhub.namespace" . }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
    app: orderhub-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: orderhub-backend
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
