apiVersion: v1
kind: Service
metadata:
  name: impulse-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: orderhub-impulse
spec:
  type: ClusterIP
  selector:
    app: orderhub-impulse
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  - name: metrics
    port: 5000
    targetPort: 5000

