apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.impulseService.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.impulseService.selector }}
spec:
  type: {{ .Values.impulseService.type }}
  selector:
    app: {{ .Values.impulseService.selector }}
  ports:
  {{- range .Values.impulseService.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  {{- end }}
