apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendService.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
    app: {{ .Values.frontendService.selector }}
spec:
  type: {{ .Values.frontendService.type }}
  selector:
    app: {{ .Values.frontendService.selector }}
  ports:
  - name: http
    port: {{ .Values.frontendService.port }}
    targetPort: {{ .Values.frontendService.targetPort }}
