apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.impulseServiceMonitor.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- toYaml .Values.impulseServiceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.impulseServiceMonitor.selector | nindent 6 }}
  endpoints:
  {{- toYaml .Values.impulseServiceMonitor.endpoints | nindent 2 }}
