apiVersion: v1
kind: Service
metadata:
  name: impulse-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: orderhub-impulse
  ports:
  - port: 8000
    targetPort: 8000
  - port: 5000
    targetPort: 5000

