apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orderhub-impulse-monitor
  namespace: orderhub-staging
  labels:
    app: orderhub-impulse
spec:
  selector:
    matchLabels:
      app: orderhub-impulse
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s