apiVersion: v1
kind: Service
metadata:
  name: orderhub-frontend-svc
  namespace: {{ include "orderhub.namespace" . }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
    app: orderhub-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: orderhub-frontend
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
