{{- if .Values.frontend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccount.name }}
  namespace: {{ include "orderhub.namespace" . }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
    app: orderhub-frontend
{{- end }}
