apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.databaseService.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "orderhub.labels" . | nindent 4 }}
    app: {{ .Values.databaseService.selector }}
spec:
  clusterIP: None
  selector:
    app: {{ .Values.databaseService.selector }}
  ports:
  - port: {{ .Values.databaseService.port }}
    targetPort: {{ .Values.databaseService.targetPort }}
