apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-component-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      istio: pilot        # per i componenti del piano di controllo, se vuoi
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring   # nome porta sul Pod (di default è "http-monitoring" per istiod)
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-stats-monitor
  namespace: monitoring
spec:
  selector:
    matchExpressions:
    - key: security.istio.io/tlsMode   # label presente sui Pod iniettati
      operator: Exists
  namespaceSelector:
    any: true
  podMetricsEndpoints:
  - port: http-envoy-prom
    path: /stats/prometheus
    interval: 15s