apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.virtualService.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  hosts:
  - {{ .Values.virtualService.host }}
  http:
  - route:
    {{- range .Values.virtualService.routes }}
    - destination:
        host: {{ $.Values.virtualService.host }}
        subset: {{ .subset }}
      weight: {{ .weight }}
    {{- end }}
