apiVersion: autoscaling/val2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpa.name }}
  namespace:  {{ .Values.namespace.name }}
spec:
  scaleTargerRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.backend.name }}
  minReplicas: {{ .Values.hpa.min }}
  maxReplicas: {{ .Values.hpa.max }}

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilizazion: {{ .Values.hpa.average }}
  
  behavior:
    scaleDown:
      selectPolicy: {{ .Values.hpa.policy2 }}
      stabilizationWindowSeconds: {{ .Values.hpa.dwin }}
      policies:
      - type: Pods
        value: {{ .Values.hpa.sdown }}
        periodSeconds: {{ .Values.hpa.downps }}
    scaleUp:
      selectPolicy: {{ .Values.hpa.policy }}
      stabilizationWindowSeconds: {{ .Values.hpa.uwin }}
      policies:
      - type: Pods
        value: {{ .Values.hpa.updown }}
        periodSeconds: {{ .Values.hpa.upps }}