apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpolicy
  namespace: notify-hub
spec:
  podSelector:
    matchLabels:
      app: notify

  policyTypes:
  - Ingress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: notifier-client
    ports:
    - protocol: TCP
      port: 8080