apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notifyhub-queue-data
  namespace: notify-hub
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: notifyhub-fast
  resources:
    requests:
      storage: 2Gi