apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notify-svc-monitor
  namespace: notifyhub
spec:
  selector:
    matchLabels:
      app: notify-svc
  endpoints:
  - port: 80
    path: /metrics
    interval: 13s