apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notify-svc-monitor
  namespace: notify-hub
spec:
  selector:
    matchLabels:
      app: notify-svc
  endpoints:
  - port: http
    path: /metrics
    interval: 13s