apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name:  {{ .Values.kreq6.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
{{ toYaml .Values.kreq6.annotations | indent 4 }}
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: pvc-size-limit
    match:
      any:
      - resources:
          kinds:
          - PersistenVolumeClaim
    validate:
      message: "PVC size can't exceed 30Gi"
      pattern:
        spec:
          resources:
            requests:
              storage: {{ .Values.kreq6.val }}