apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        resource:
          limits:
            memory: {{ .Values.backend.rlm }}
            cpu: {{ .Values.backend.rlc }}
          requests:
            memory: {{ .Values.backend.rrm }}
            cpu: {{ .Values.backend.rrc }}
        livenessProbe:
          httpGet:
            path: /path
            port: {{ .Values.backend.port}}
          
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.backend.port}}

        securityContext:
            runAsNonRoot: true
            allowPriviledgeEscalation: false
            capabilites:
              drop: ["ALL"]  
              
        envFrom:
          - secretRef:
              name: {{ .Values.secret.secname }}
          - configMapRef:
              name: {{ .Values.cmap.mapname }}
        
          