apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.limit.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  limits:
  - default:
      memory: {{ .Values.limit.defl.m }}
      cpu: {{ .Values.limit.defl.c }}
    defaultRequest:
      memory: {{ .Values.limit.defR.m }}
      cpu: {{ .Values.limit.defR.c }}
    max:
      memory: {{ .Values.limit.max.m }}
      cpu: {{ .Values.limit.max.c }}
    min:
      memory: {{ .Values.limit.min.m }}
      cpu: {{ .Values.limit.min.c }}
    type: {{ .Values.limit.type }}