apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicebackend.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.servicebackend.type }}
  selector:
    app: {{ .Values.deploymentaggregator.name }}
  ports:
    - port: {{ .Values.servicebackend.port }}
      targetPort: {{ .Values.servicebackend.targetport }}
      
  