apiVersion: v1
kind: ConfigMap
metadata:
  name: tradex-config
  namespace: {{ include "tradex.namespace" . }}
  labels:
    {{- include "tradex.labels" . | nindent 4 }}
data:
  db-host: {{ .Values.config.dbHost | quote }}
  db-port: {{ .Values.config.dbPort | quote }}
  db-user: {{ .Values.config.dbUser | quote }}
  db-name: {{ .Values.config.dbName | quote }}
  log-level: {{ .Values.config.logLevel | quote }}
