apiVersion: v1
kind: Service
metadata:
  name: tradex-backend-svc
  namespace: {{ include "tradex.namespace" . }}
  labels:
    {{- include "tradex.labels" . | nindent 4 }}
    app: tradex-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: tradex-backend
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
