apiVersion: v1
kind: Service
metadata:
  name: tradex-db-svc
  namespace: {{ include "tradex.namespace" . }}
  labels:
    {{- include "tradex.labels" . | nindent 4 }}
    app: tradex-db
spec:
  clusterIP: None
  selector:
    app: tradex-db
  ports:
  - port: {{ .Values.database.service.port }}
    targetPort: {{ .Values.database.service.targetPort }}
