apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadb
  namespace: orderhub-pro
spec:
  storageClassName: orderhub-pro-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi