apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orderhubpro-backend-monitor
  namespace: orderhub-pro
spec:
  selector:
    matchLabels:
      app: backendpro-svc
  endpoints:
  - port: 5000
    path: /metrics
    interval: 15s