name: Build and Push Backend Image

on:
  push:
    branches:
      - main
    paths:
      - 'orderhub/docker/backend/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: orderhub/docker/backend
          file: orderhub/docker/backend/back
          push: true
          tags: 192.168.0.23:5000/orderhub-backend:${{ github.sha }}

      - name: Update values.yaml with new tag
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
          sed -i "s|tag:.*|tag: ${{ github.sha }}|" orderhub/values.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add orderhub/values.yaml
          git commit -m "Update backend image tag to ${{ github.sha }}"
          git push origin main