name: Build and Push Backend Images

concurrency:
  group: build-backend
  cancel-in-progress: false

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        project:
          - name: orderhub
            context: orderhub/docker/backend
            dockerfile: orderhub/docker/backend/back
            image: 192.168.0.23:5000/orderhub-backend
            values: orderhub/values.yaml
          - name: orderhub
            context: orderhub/docker/frontend
            dockerfile: orderhub/docker/frontend/back
            image: 192.168.0.23:5000/orderhub-frontend
            values: orderhub/values.yaml

    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.project.context }}
          file: ${{ matrix.project.dockerfile }}
          push: true
          tags: ${{ matrix.project.image }}:${{ github.sha }}

      - name: Update values.yaml with new tag
        run: |
          sed -i "s|tag:.*|tag: ${{ github.sha }}|" ${{ matrix.project.values }}
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ${{ matrix.project.values }}
          git commit -m "Update ${{ matrix.project.name }} backend tag to ${{ github.sha }}"
          for i in 1 2 3 4 5; do
            git push origin main && break
            git fetch origin main
            git rebase origin/main
            sleep 3
          done