apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metricstore-disk
  namespace: metricstore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: metricstore-sc