apiVersion: apps/v1
kind: Deployment
metadata:
  name: minishop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minishop-backend
  template:
    metadata:
      labels:
        app: minishop-backend
    spec:
      containers:
        - name: minishop
          image: nginx:latest
          ports:
            - containerPort: 80